version: '3.5'
services:
  api:
    image: api
    build:
      context: ./
      dockerfile: ./src/Dockerfile
    ports:
      - '3000:3000'
    networks:
      - dev-network

  
  database:
    image: mysql:latest
    container_name: database
    env_file:
      - .env
    ports:
      - '3306:3306'
    volumes:
      - ./data:/var/lib/mysql
    networks:
      - dev-network

networks:
  dev-network:
    driver: bridge